# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
  gt: $(GHPat)
trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:

- script: |
    mkdir -p images
    npm i mermaid.cli
    ls -al
    ./build-diagrams.sh && \
    git checkout master && \
    git add . && \
    git commit -m "Updating images" && \
    git push https://%gt%@github.com/esdc-devx/Diagrams.git

  displayName: 'Build Image'
