# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
  gt: $(GHPat)
trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    sudo npm install -g mermaid.cli
  displayName: Installing mermaid cli
- script: |
    mkdir -p images
    ./build-diagrams.sh && \
    git checkout master && \
    git config --global user.email "calvin.rodo@hrsdc-rhdcc.gc.ca" && \
    git config --global user.name "Calvin Automated Build" && \
    git add . && \
    git commit -m "Updating images" && \
    git push https://%gt%@github.com/esdc-devx/Diagrams.git
  displayName: 'Build Image'
